spring.application.name=s3-server

server.port=9000

# ===============================
# MySQL Database
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/repo2cloud_s3
spring.datasource.username=YOUR_MYSQL_USERNAME
spring.datasource.password=YOUR_MYSQL_PASSWORD


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# S3 Local Storage
# ===============================

s3.storage.root=./s3-storage